In [1]:
#import numpy library
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
#type of array in numpy
type(arr)

numpy.ndarray

In [4]:
#dimension of the array
arr.ndim

1

In [5]:
#shape of the array
arr.shape

(5,)

In [6]:
#check the function type
arr.max

<function ndarray.max>

In [7]:
#find the max number from the array
arr.max()

5

In [8]:
#importing time and sys
import time
import sys

In [12]:
#time analysis
list1 = range(1000000)
arr1 = np.arange(1000000)

In [19]:
start = time.time() * 1000

result = [(x,y) for x, y in zip(list1,list1)] 

end = time.time() * 1000

op1 = end - start

In [20]:
start = time.time() * 1000

result = arr1 + arr1

end = time.time() * 1000

op2 = end - start

In [23]:
print(op1, op2)


289.469970703125 86.466064453125


In [25]:
#check the size of each element of ndarray
arr1.itemsize

8

In [26]:
#check the shape of the array
arr1.shape

(1000000,)

In [27]:
#check the data type of the elements of the ndarray
arr1.dtype

dtype('int64')

In [32]:
#check the size of the ndarray
arr1.size

1000000

In [37]:
#get the memory address of the ndarray
arr1.data

In [40]:
#get the total memory occupied by the array
(arr1.nbytes/1024)/1024

7.62939453125

In [41]:
zarr =  np.zeros((4,4), dtype=np.float64)

In [42]:
zarr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
zarr.ndim

2

In [45]:
zarr.shape

(4, 4)

In [47]:
oarr = np.ones((4,4), dtype=np.int32)
oarr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [53]:
iarr = np.eye(4, dtype=np.int32)
iarr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [55]:
np.add(oarr , iarr)

array([[2, 1, 1, 1],
       [1, 2, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 2]], dtype=int32)

In [56]:
oarr + iarr

array([[2, 1, 1, 1],
       [1, 2, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 2]], dtype=int32)

In [63]:
np.multiply(oarr , iarr)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [64]:
oarr.size

16

In [66]:
oarr.ravel()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [67]:
iarr.flatten()

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int32)

In [ ]:
np.log